import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

// The API dev server runs on this port (see server/.env.example). In development the browser
// talks to the Vite origin and Vite proxies /api to Express, so there are no CORS or cookie
// cross-origin problems. Production uses the same idea via the reverse proxy.
const API_PROXY_TARGET = process.env.VITE_DEV_API_TARGET ?? "http://localhost:4000";

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
  server: {
    // A dedicated port for this project (other projects on the same machine use 5173+). strictPort makes
    // Vite fail loudly instead of silently moving to a port that belongs to someone else.
    port: Number(process.env.VITE_DEV_PORT ?? 5273),
    strictPort: true,
    proxy: {
      "/api": { target: API_PROXY_TARGET, changeOrigin: false },
      // Crawler files are generated by the API from configuration and data.
      "/robots.txt": { target: API_PROXY_TARGET, changeOrigin: false },
      "/sitemap.xml": { target: API_PROXY_TARGET, changeOrigin: false },
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    include: ["src/**/*.test.{ts,tsx}"],
    css: false,
  },
});
